
import { useWithAuthContext } from 'lib/context'
import type { NextPage } from 'next'
import Head from 'next/head'
const Home: NextPage = () => {
  const { user } = useWithAuthContext()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ? <p>Hello {JSON.stringify(user, null, 4)}</p> : <p>Hello stranger</p>}
    </div>
  )
}



export default Home
